<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!--#if (supportBrowser) -->
  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>
  <!--#endif -->

  <ItemGroup>
    <PackageReference Include="Moka.Red" Version="0.1.10" />
  </ItemGroup>

</Project>
